### PR TITLE
Adding information about RDF checker library

### PR DESCRIPTION
**Pull request by I-Sokolov**

### CODE REVIEW

**Comment by CBenghi** [comment]
Hello @I-Sokolov,
is there a link to a more specific page for IDS?
In principle we will want this for all libraries, of course.
Thanks,
Claudio

**Comment by I-Sokolov** [comment]
Hi Peter

As I understand Claudio asks a page on rdf.bg that specifically describes IDS support details.

Could you please reply on PR comment  <https://github.com/buildingSMART/IDS/pull/231#issuecomment-1923689458> Adding information about RDF checker library by I-Sokolov · Pull Request #231 · buildingSMART/IDS (github.com)

Thanks

               Igor

**Comment by peterrdf** [comment]
Hi @I-Sokolov and @CBenghi, the most logical part where we can further describe this IDS support is our documentation I guess. I will have a look, Thanks.

**Comment by CBenghi** [comment]
Hello @peterrdf,
did you find a better URL that we can use?
PS Note that the documentation page was edited and the PR is now conflicting, could you please resolve?

**Review by berlotti — APPROVED** [review]

**Comment by berlotti** [comment]
Please use https://technical.buildingsmart.org/resources/software-implementations/

**Pull request closed without merging**
