### PR TITLE
Regenerate test cases

### PR DESCRIPTION
**Pull request by aothms**
I've reran the generation scripts. There's quite a few things coming in. Including new test cases. I haven't followed things closely enough to judge so please review carefully.

### CODE REVIEW

**Comment by CBenghi** [comment]
Hi @aothms, 
there's an issue with `schemalocation` of the files.

`xsi:schemaLocation="http://standards.buildingsmart.org/IDS/0.9.6/ids.xsd"`
should read
`xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/0.9.6/ids.xsd"`

The first part of the string being the namespace, the second being the publication URL (space separated).
In the medium term we need to define if we want to be strict on the protocol.

I'm now looking at a number of other failures, but changing the tool to make it easier to communicate.

**Comment by aothms** [comment]
Cool. xsi:schemaLocation changed accordingly

**Comment by andyward** [comment]
Do we need to get to the bottom of whether Attributes have cardinality -  before fixing up the Attribute tests? We've lost the ability to prohibit values in attributes, which some of the test cases relied on. See: Dion's comment https://github.com/buildingSMART/IDS/issues/144#issuecomment-1704597763

**Comment by Moult** [comment]
Agreed I think we should bring back the attribute cardinality first.

**Comment by aothms** [comment]
Has my blessing

**Comment by CBenghi** [comment]
Hello all,

I've added a temporary hack to the audit tool that omits the errors on cardinality for `attribute` entities and improves the feedback so that @aothms and @Moult (and myself once I learn how to). Can tidy them up.

If you see the details of the failing checks you and expand the `AuditDocTestCases` node, you can see the problems.

Looking out for `fail` markers in the log like the following:

```
08:26:42 [DBG] info: idsTool.Program[0] Auditing file: `/home/runner/work/IDS/IDS/Documentation/testcases/attribute/fail-specifying_a_float_when_the_value_is_an_integer_will_fail.ids`.
08:26:42 [DBG] fail: idsTool.Program[0] Error 103: Invalid value `NumberOfRisers` to match `attribute names` (668 accepted values exist, starting with ActingRole, ActionSource, ActionType, ActualDuration, ActualFinish...) in the context of Ifc2x3, Ifc4 on 'simpleValue' element at line 17, position 26.
```

The feedback is a little more readable if you execute the tool locally, with a command similar to `ids-tool.exe audit C:\Data\Dev\BuildingSmart\IDS\Documentation\testcases -p "\\fail-" -x "C:\Data\Dev\BuildingSmart\IDS\Development\ids.xsd"`

I hope this helps,
Claudio

**Comment by andyward** [comment]
Can we make sure #226 / #108 gets picked up with this regeneration? - it seems multiple implementors are getting issues with some incorrect data in the classification test cases. I put some notes on the 226 PR about the exact issue and a potential fix.

**Pull request closed without merging**
