### PR TITLE
Update pass-a_classification_facet_with_no_data_matches_any_classific…

### PR DESCRIPTION
**Pull request by rubendel**
…ation_2_2.ifc

Removed one wall that was not being referenced by any IFCCLASSIFICATIONREFERENCE, which for me made the test case fail although it should pass. Any feedback appreciated if my thinking is not correct here.

### CODE REVIEW

**Comment by Moult** [comment]
Sorry this is an error in the spec generator, where the tests only check a single element. I've done a fix and will commit. This error will also affect other testcases, so don't worry about submitting PRs for them until I've committed the fix.

**Comment by rubendel** [comment]
Awesome thanks. I noticed there are a few more later on. I guess you could also have the 4th classification reference refer to the 4th wall instead of to IfcProject, I guess that's probably what was intented.

**Comment by rubendel** [comment]
Hey @Moult I looked at the new files, but for example this one seems to be wrong again, maybe I am too early?

**Comment by Moult** [comment]
Looks correct to me? https://github.com/buildingSMART/IDS/blob/master/Documentation/testcases-classification.md#pass-a-classification-facet-with-no-data-matches-any-classification-22

**Comment by rubendel** [comment]
Sorry my bad, was working with stale IFC files, appreciate the fixes.

**Pull request merged**
